
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-bridge
  namespace: strimzi
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: tls
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: kafka-bridge
  namespace: strimzi
spec:
  bootstrapServers: kafka-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: kafka-cluster-ca-cert
        certificate: ca.crt
  authentication:
    type: tls
    certificateAndKey:
      secretName: kafka-bridge
      certificate: user.crt
      key: user.key
  http:
    port: 8080 
  enableMetrics: true

