
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: topic-mongo
  namespace: strimzi
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 2
  config:
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: topic-bucket
  namespace: strimzi
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 2
  config:
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: topic-psql
  namespace: strimzi
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 2
  config:
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: connect-cluster-offsets
  namespace:  strimzi
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 2
  config:
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: connect-cluster-configs
  namespace:  strimzi
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 2
  config:
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: connect-cluster-status
  namespace:  strimzi
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 2
  config:
    cleanup.policy: compact
