apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ingress-apisix
  namespace: ingress-apisix
  labels:
    use-for: ingress-apisix
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-controller
  podMetricsEndpoints:
  - port: http
