apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grafana--internet--any--ingress--ports--3000-9090--nr65
  namespace: grafana
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 3000
    - protocol: TCP
      port: 9090
