apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minio--all--minio--egress--ports--minio--nr55
  namespace: minio
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          stacktic.io/namespace: minio
