apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus--internet--any--ingress--ports--3000-9090--nr63
  namespace: prometheus
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 3000
    - protocol: TCP
      port: 9090
