apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grafana--internet--any--egress--ports--80-443-9090--nr66
  namespace: grafana
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: TCP
      port: 80
      port: 443
      port: 9090
    - protocol: TCP
      port: 443
