apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus--internet--any--egress--ports--80-443--nr64
  namespace: prometheus
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
