apiVersion: 1

datasources:
  - name: prometheus
    uid: prometheus
    type: prometheus
    url: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
    access: proxy
    isDefault: true
