resources:
  - namespace.yaml
  - postgresql.yaml
  - jobs/data-job.yaml
  - jobs/clean-job-cron.yaml
  

secretGenerator:
  - name: postgresql-initdb
    namespace: postgresql
    files:
      - config/initdb.sql
  - name: postgresql-admin-password
    namespace: postgresql
    envs:
      - secret/postgresql.env

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      stacktic.io/app: "postgresql"
      stacktic.io/group: "rel_db"
      stacktic.io/namespace: "postgresql"
    includeTemplates: true
