---
# Source: grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: "grafana"
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.0.0
    helm.sh/chart: grafana-11.2.0
secrets:
  - name: grafana-admin-password
  - name: grafana-datasources
automountServiceAccountToken: false
---
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-envvars
  namespace: "grafana"
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.0.0
    helm.sh/chart: grafana-11.2.0
    app.kubernetes.io/component: grafana
data:
  GF_SECURITY_ADMIN_USER: "admin"
  GF_INSTALL_PLUGINS: ""
  GF_PATHS_PLUGINS: "/opt/bitnami/grafana/data/plugins"
  GF_AUTH_LDAP_ENABLED: "false"
  GF_AUTH_LDAP_CONFIG_FILE: "/opt/bitnami/grafana/conf/ldap.toml"
  GF_AUTH_LDAP_ALLOW_SIGN_UP: "false"
  GF_PATHS_PROVISIONING: "/opt/bitnami/grafana/conf/provisioning"
  GF_PATHS_CONFIG: "/opt/bitnami/grafana/conf/grafana.ini"
  GF_PATHS_DATA: "/opt/bitnami/grafana/data"
  GF_PATHS_LOGS: "/opt/bitnami/grafana/logs"
---
# Source: grafana/templates/dashboard-provider.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provider
  namespace: "grafana"
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.0.0
    helm.sh/chart: grafana-11.2.0
    app.kubernetes.io/component: grafana
data:
  default-provider.yaml: |-
    apiVersion: 1

    providers:
      # <string> an unique provider name
    - name: 'default-provider'
      # <int> org id. will default to orgId 1 if not specified
      orgId: 1
      # <string, required> name of the dashboard folder. Required
      folder: dashboards
      # <string> folder UID. will be automatically generated if not specified
      folderUid: ''
      # <string, required> provider type. Required
      type: file
      # <bool> disable dashboard deletion
      disableDeletion: false
      # <bool> enable dashboard editing
      editable: true
      # <int> how often Grafana will scan for changed dashboards
      updateIntervalSeconds: 10
      options:
        # <string, required> path to dashboard files on disk. Required
        path: /opt/bitnami/grafana/dashboards
        # <bool> enable folders creation for dashboards
        #foldersFromFilesStructure: true
---
# Source: grafana/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana
  namespace: "grafana"
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.0.0
    helm.sh/chart: grafana-11.2.0
    app.kubernetes.io/component: grafana
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
# Source: grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: "grafana"
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.0.0
    helm.sh/chart: grafana-11.2.0
    app.kubernetes.io/component: grafana
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: 3000
      targetPort: dashboard
      protocol: TCP
      name: http
      nodePort: null
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: grafana
---
# Source: grafana/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: "grafana"
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.0.0
    helm.sh/chart: grafana-11.2.0
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: grafana
      app.kubernetes.io/name: grafana
      app.kubernetes.io/component: grafana
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: grafana
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: grafana
        app.kubernetes.io/version: 11.0.0
        helm.sh/chart: grafana-11.2.0
        app.kubernetes.io/component: grafana
      annotations:
        checksum/config: 21ec65c21d14fb0d8f82c84b9be019dcd8ddb638913dc957621d007038ef7975
        checksum/dashboard-provider: a8ec6e32167c04f2806236c43a2252ed9cf7e8a8203c153852cdb0d80ef84b75
    spec:
      
      automountServiceAccountToken: false
      serviceAccountName: grafana
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: grafana
                    app.kubernetes.io/name: grafana
                    app.kubernetes.io/component: grafana
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      enableServiceLinks: true
      initContainers:
      containers:
        - name: grafana
          image: docker.io/bitnami/grafana:11.0.0-debian-12-r0
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          envFrom:
            - configMapRef:
                name: grafana-envvars
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-password
                  key: password
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/grafana/conf
              subPath: app-conf-dir
            - name: empty-dir
              mountPath: /opt/bitnami/grafana/tmp
              subPath: app-tmp-dir
            - name: empty-dir
              mountPath: /bitnami/grafana
              subPath: app-volume-dir
            - name: data
              mountPath: /opt/bitnami/grafana/data
            - name: dashboards-provider
              mountPath: /opt/bitnami/grafana/conf.default/provisioning/dashboards
            - name: dashboard-kubernetes
              mountPath: /opt/bitnami/grafana/dashboards/kubernetes.json
              subPath: kubernetes.json
            - name: dashboard-jvm
              mountPath: /opt/bitnami/grafana/dashboards/jvm.json
              subPath: jvm.json
            - name: dashboard-kube-state-metrics
              mountPath: /opt/bitnami/grafana/dashboards/kube-state-metrics.json
              subPath: kube-state-metrics.json
            - name: dashboard-mongodb
              mountPath: /opt/bitnami/grafana/dashboards/mongodb.json
              subPath: mongodb.json
            - name: dashboard-kafka-broker
              mountPath: /opt/bitnami/grafana/dashboards/kafka-broker.json
              subPath: kafka-broker.json
            - name: dashboard-kafka-kraft
              mountPath: /opt/bitnami/grafana/dashboards/kafka-kraft.json
              subPath: kafka-kraft.json
            - name: dashboard-kafka-exporter
              mountPath: /opt/bitnami/grafana/dashboards/kafka-exporter.json
              subPath: kafka-exporter.json
            - name: dashboard-kafka-connect
              mountPath: /opt/bitnami/grafana/dashboards/kafka-connect.json
              subPath: kafka-connect.json
            - name: dashboard-kafka-bridge
              mountPath: /opt/bitnami/grafana/dashboards/kafka-bridge.json
              subPath: kafka-bridge.json
            - name: dashboard-kafka-operators
              mountPath: /opt/bitnami/grafana/dashboards/kafka-operators.json
              subPath: kafka-operators.json
            - name: datasources
              mountPath: /opt/bitnami/grafana/conf.default/provisioning/datasources
          ports:
            - name: dashboard
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: dashboard
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /api/health
              port: dashboard
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          resources:
            limits:
              cpu: 375m
              memory: 384Mi
            requests:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: data
          persistentVolumeClaim:
            claimName: grafana
        - name: dashboards-provider
          configMap:
            name: grafana-provider
        - name: dashboard-kubernetes
          configMap:
            name: dashboard-kubernetes
        - name: dashboard-jvm
          configMap:
            name: dashboard-jvm
        - name: dashboard-kube-state-metrics
          configMap:
            name: dashboard-kube-state-metrics
        - name: dashboard-mongodb
          configMap:
            name: dashboard-mongodb
        - name: dashboard-kafka-broker
          configMap:
            name: dashboard-kafka-broker
        - name: dashboard-kafka-kraft
          configMap:
            name: dashboard-kafka-kraft
        - name: dashboard-kafka-exporter
          configMap:
            name: dashboard-kafka-exporter
        - name: dashboard-kafka-connect
          configMap:
            name: dashboard-kafka-connect
        - name: dashboard-kafka-bridge
          configMap:
            name: dashboard-kafka-bridge
        - name: dashboard-kafka-operators
          configMap:
            name: dashboard-kafka-operators
        - name: datasources
          secret:
            secretName: grafana-datasources
