{
 "title": "MongoDB",
 "description": "MongoDB",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "component_name",
    "label": "Component Name",
    "query": {
     "query": "label_values(mongodb_connections,component_name)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(mongodb_connections{component_name=~\"$groups|$component_name\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "uptime",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "DB-VERSION",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_version_info{instance=~\"$instance\"}",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  {
   "title": "Total number of page faults for disk operations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_extra_info_page_faults_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Cluster health",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "mongodb_mongod_replset_member_health{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{name}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_state{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Cache Overhead",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_overhead_percent{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Mongodb Status",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Number of Timed-out Cursors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_cursor_timed_out_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Virtual Memory\n",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_memory{instance=~\"$instance\",type=~\"virtual\"}"
    }
   ]
  },
  {
   "title": "Number of databases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mongodb_mongod_db_data_size_bytes{ instance=~\"$instance\",db!=\"local\",db!=\"admin\"})"
    }
   ]
  },
  {
   "title": "physical memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_memory{instance=~\"$instance\",type=~\"resident\"}"
    }
   ]
  },
  {
   "title": "Database operations",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Number of Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_connections{instance=~\"$instance\",state=~\"current|available\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Client read and write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_client{instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "read-write lock",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mongodb_mongod_global_lock_current_queue{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "File operations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Primary-Secondary synchronization delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_replication_lag{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cache data size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Oplog Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_oplog_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}